### ISSUE TITLE
Not Working since 10.05.2017

### ISSUE THREAD

**Issue by suyashbansal** [suyashbansal/Way2SMS-API#2]
_From @cpl2015 on May 28, 2017 10:42_

Since 10th May 2017, this API is not working. It shows 'invalid login'. Please fix. Thank You.

_Copied from original issue: suyashbansal/Way2SMS-API#4_

**Comment by suyashbansal** [comment]
Sure. I'll have a look.

**Comment by suyashbansal** [comment]
It is fixed now. 😄

**Comment by cpl2015** [comment]
Thank You very much.
